### PR TITLE
All other changes..

### PR DESCRIPTION
**Pull request by NatarajBTI**
All other changes..

### CODE REVIEW

**Review by padmankosalaram — APPROVED** [review]

**Comment by ocofaigh** [comment]
This PR contains issues that have been requested in https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/82 - please close this PR and use that one to make the changes to avoid duplicating PR reviews

**Comment by NatarajBTI** [comment]
> This PR contains issues that have been requested in #82 - please close this PR and use that one to make the changes to avoid duplicating PR reviews

@ocofaigh - You mean this PR #92 right? Which I closed it just a while back thinking will followup with this PR..will reopen #92..

**Comment by ocofaigh** [comment]
yes sorry please use https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/92

**Pull request closed without merging**
