### PR TITLE
add workaround to tests

### PR DESCRIPTION
**Pull request by ocofaigh**
### Description

Add workaround for https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/78

### Release required?

- [x] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by NatarajBTI — DISMISSED** [review]
I approve..

**Comment by ocofaigh** [comment]
Pipeline failed due to https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/83
Going to retry to see if it passes on retry

**Comment by ocofaigh** [comment]
Ahh I know whats wrong - I need to find another way to fix this..

**Comment by ocofaigh** [comment]
Pipeline failed due to another intermittent issue: https://github.com/terraform-ibm-modules/terraform-ibm-mas/issues/90

**Comment by ocofaigh** [comment]
Pipeline hit this issue again: https://github.com/terraform-ibm-modules/terraform-ibm-mas/actions/runs/8946518936/job/24577343472

Will retry..

**Comment by ocofaigh** [comment]
This time pipeline failed with:

```
│ Detected the following failed task(s):
│ inst1-install-m5chh-cluster-monitoring
│ Exiting.
```

Retrying ..

**Comment by ocofaigh** [comment]
Closing in favour of https://github.com/terraform-ibm-modules/terraform-ibm-mas/pull/91

**Pull request closed without merging**
